service: crypto-correlation
frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.7
  lambdaHashingVersion: '20201221'

functions:
  correlationLambda:
    handler: lambda-handler.handle
    events:
      - http:
          path: /correlated-assets
          method: post
