service: crypto-correlation
frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'

functions:
  getCorrelatedAssets:
    handler: lambda-handler.handle
    events:
      - http:
          path: /
          method: get
